// =============================================================
// 
// 	book_list.js
// this file is known as a CONTAINER
// a CONTAINER is a react component that has a direct connection to the STATE (generated by reducers) managed by redux
// esentially, containers are components that handle data that comes from the react state
// =============================================================


import React, { Component } from 'react';

class BookList extends Component {

	// this will set up the function to render our list
	// we will be adding the list of books to our props object later
	renderList(){

		// creates the const for our boooks prop for re-use
		const books = return this.props.books;

		// creates the map of the books array, setting up an object for each index and calling it 'book'
		books.map((book) => {

			// returns our book properties within an li
			return (
				<li key={book.title} className="list-group-items">
					
					{book.title}

				</li>
			);
		})
	}


	// this sets up the component for our booklist's HTML
	render(){

		<ul className="list-group col-sm-4">
			{this.renderList()}
		</ul>
	}

};

export default bookList;